### ISSUE TITLE
Retain BFO hiearchy on import of OBI term protocol

### ISSUE THREAD

**Issue by andredekker** [aapm-bdsc-ontology-tg/rto#18]
Imported terms (e.g. from IAO, OBI etc.) are not placed in the BFO hierarchy. This issues changes the import settings so that the basic hierarchy is maintained in upon import.

Steps for OBI import
1. Note the superclasses of an imported terms until you reach a BFO class. E.g. OBI_0000272 (protocol) has superclass IAO_0000104 (plan specification) which has superclass IAO_0000033 (directive information entity) which has superclass IAO_0000030 (incormation content entity) which has superclass BFO_0000031
2. Change the rto-odk.yaml file to include all the relevant base URIs (of the classes of step 1). E.g. 
```
   - id: obi
     module_type: filter
     base_iris:
       - http://purl.obolibrary.org/obo/OBI_
       - http://purl.obolibrary.org/obo/BFO_
       - http://purl.obolibrary.org/obo/IAO_
``` 
3. Update repository
``` 
sh run.sh make update_repo
``` 
4. Add the terms of step 1 to obi_terms.txt file 
``` 
IAO:0000104
IAO:0000033
IAO:0000030
BFO:0000031
``` 
5. Update the import file
``` 
sh run.sh make refresh-obi
``` 

Result:

Before:
![before](https://github.com/aapm-bdsc-ontology-tg/rto/assets/2337314/a884d25b-8908-437f-b168-8abddc949fb0)

After:
![after](https://github.com/aapm-bdsc-ontology-tg/rto/assets/2337314/4a86c6e8-0608-4132-a5a7-b99c18069ef9)
